server:
  port: 7899


spring:
    datasource:
        name: test
        url: jdbc:mysql://47.106.149.105:3306/zjb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    servlet:
        multipart:
            max-file-size: 10Mb
            max-request-size: 30Mb
    data:
      mongodb:
        host: 47.106.149.105
        port: 27017
#        uri: mongodb://47.106.149.105:27017
#        username: admin
#        password: 123
        database: zjb

#        authentication-database: admin
#        uri: mongodb://admin:123@47.106.149.105:27017/zjb

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.renchaigao.zujuba.model

mapper:
  mappers:  com.renchaigao.zujuba.dao.mapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check




